// Generated by scripts/import-trails.mjs — do not edit.
export const TRAIL_GEO: Record<string, () => Promise<{ default: unknown }>> = {
  "annapurna-circuit--annapurna-base-camp": () => import("@content/trail-geo/annapurna-circuit--annapurna-base-camp.json"),
  "annapurna-circuit--annapurna-circuit-trek": () => import("@content/trail-geo/annapurna-circuit--annapurna-circuit-trek.json"),
  "annapurna-circuit--mardi-himal": () => import("@content/trail-geo/annapurna-circuit--mardi-himal.json"),
  "mount-fuji--fujinomiya-trail": () => import("@content/trail-geo/mount-fuji--fujinomiya-trail.json"),
  "mount-fuji--gotemba-trail": () => import("@content/trail-geo/mount-fuji--gotemba-trail.json"),
  "mount-fuji--subashiri-trail": () => import("@content/trail-geo/mount-fuji--subashiri-trail.json"),
  "yosemite-national-park--four-mile-trail": () => import("@content/trail-geo/yosemite-national-park--four-mile-trail.json"),
  "yosemite-national-park--mist-trail": () => import("@content/trail-geo/yosemite-national-park--mist-trail.json"),
  "yosemite-national-park--sentinel-dome": () => import("@content/trail-geo/yosemite-national-park--sentinel-dome.json"),
  "yosemite-national-park--upper-yosemite-fall": () => import("@content/trail-geo/yosemite-national-park--upper-yosemite-fall.json"),
};
